### PR TITLE
Add support for local infile handlers

### PR DESCRIPTION
**Pull request by Diggsey**
This PR lets you set a custom "local infile handler" for a connection. Subsequent requests from the server for a local file will be redirected to this handler. This allows for very fast insertion of data.

### CODE REVIEW

**Comment by blackbeam** [comment]
Consider the following code:

```rust
let pool = my::Pool::new(opts);
{
    let mut transaction = pool.start_transaction(...);
    transaction.set_local_infile_handler(...);
    // ...
}
let conn = pool.get_conn(); // Will this connection have handler or not?
```

We can add call to `clear_local_infile_handler` to `Transaction` drop implementation but in this case it will implicitly clear handler if it was set via `Conn::set_local_infile_handler`.

I propose to:

- Change `set_local_infile_handler()` in a way that it could remove existing handler (i.e. set `conn.local_infile_hanlder` to `None`)
- Remove `clear_local_infile_handler()` from `Transaction`.
- Change `Transaction::set_local_infile_handler` in a way that it will store original handler.
- Change `Transaction::drop()` in a way that it will restore original handler.
- Add `local_infile_handler()` to `OptsBuiler` (as a way to set "default" handler for new connections).
- Add `get_local_infile_handler()` to `Opts`.
- Add `set_local_infile_handler()` and `clear_local_infile_handler()` to `PooledConn` (for convenience)
- Change `clear_local_infile_handler` in a way that it will restore "default" handler stored in `Opts`.
- Add call to `clear_local_infile_handler` to `PooledConn` drop implementation.
- Mention behavior in documentation. 

What do you think?

**Comment by Diggsey** [comment]
> Change set_local_infile_handler() in a way that it could remove existing handler (i.e. set conn.local_infile_hanlder to None)
> Remove clear_local_infile_handler() from Transaction.

The issue with that is that rust will likely be unable to deduce the type parameter if `None` is passed (even though it should be irrelevant).

The rest of your suggestions are good though, and I'll update the PR.

**Comment by Diggsey** [comment]
I decided to wrap the callback in the `LocalInfileHandler` struct which avoids the problem above and also the need to repeat the complex `FnMut` trait bounds everywhere.

**Comment by blackbeam** [comment]
Thanks!

**Comment by blackbeam** [comment]
Published as v7.1.1 (i messed up a little)

**Pull request merged**
