### PR TITLE
Use utf8mb4 by default

### LINKED ISSUE #60: 4-byte utf-8 codepoints not supported
The `utf8` charset encoding in MySQL is broken (it only supports up to 3-byte codepoints) and the "fixed" charset is called `utf8mb4`. By default this library seems to use `utf8`, which results in not being able to insert some characters into the database

### PR DESCRIPTION
**Pull request by Diggsey**
Fixes #60

### CODE REVIEW

**Comment by blackbeam** [comment]
Thanks for contribution.
But it looks like it requires Mysql >=5.5.3 and Mariadb >=5.5. Could you please look into *server version* field of an initial handshake packet and fall back to utf8 if it is too old?

**Comment by Diggsey** [comment]
Yep, done!

**Comment by blackbeam** [comment]
Please add this comment to #36 before i merge:

> I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Diggsey** [comment]
@blackbeam You should add the contribution section to your README, then there's no need to have future contributors add to that thread.

**Pull request merged**
