### PR TITLE
feat: add get_opt and take_opt to row

### PR DESCRIPTION
**Pull request by zacharygolba**
It's useful to have a non-panicking way to get column values from a row. Nullable columns seem to fail with the traditional `.{get|take}` methods.

### CODE REVIEW

**Comment by blackbeam** [comment]
Hi! Sorry for late response. I'm on vacation at the moment.

I don't like it because with this approach there is no way to distinguish between conversion error and value absence. Also `from_value_opt` gives a way to recover original value in case of error but `take_opt` does not. 

BTW there exists `impl<T: FromValue> FromValue for Option<T>` specifically for nullable columns. All other conversion errors is for cases when type is wrong and does not match column type (i.e. programmer's error) or column type is unknown and one wants to probe it (which is possible but quite unusual).

**Comment by zacharygolba** [comment]
> I don't like it because with this approach there is no way to distinguish between conversion error and value absence.

Yeah in hindsight blindly converting to an option with `.ok` wasn't the best idea.

> BTW there exists `impl<T: FromValue> FromValue for Option<T>` specifically for nullable columns.

Ah good to know!

There are a few edge cases where I would like to define a default value for a struct field that implements `FromRow`. In these cases the default value for the application does not match the general case for all of the other applications that use the database so setting a default value for the column is out of the question. Ideally I would be able to intercept `Option<T> where T: FromValue` so I could call `.unwrap_or` on `Option<T>`.

Is there a way to implement that behavior with the current API?

**Comment by blackbeam** [comment]
Hi again! My vacation is finally over.

> There are a few edge cases where I would like to define a default value for a struct field that implements FromRow. In these cases the default value for the application does not match the general case for all of the other applications that use the database so setting a default value for the column is out of the question. Ideally I would be able to intercept Option<T> where T: FromValue so I could call .unwrap_or on Option<T>.

I'm not sure that i understand you correctly. Could you please give a simple illustration if this question is still relevant?

**Comment by zacharygolba** [comment]
Hey, I hope you had a nice vacation! I included a simple example below. It's a bit of an edge case but I imagine there are many more uses for such logic. Let me know if you need more context.

```rust
// Imagine we have a `posts` table has 2 body columns, one of which is a remnant of
// an old system. Ideally there would be away to fallback to other columns or default
// values that may not be expressed in the database schema.
post.body = row.take_opt("body")
               .or_else(|| row.take_opt("legacy_body_column"))
               .unwrap_or_default();
```

**Comment by blackbeam** [comment]
For this case and if column order is known i'd use `FromRow` followed by `or_else`.

```rust
let (body, legacy_body) = from_row::<(Option<String>, Option<String>)>(row);
post.body = body.or(legacy_body).unwrap_or_default();
```

For other cases your approach should work:

```rust
post.body = row.take::<Option<String>, _>("body")
               .or_else(|| row.take::<Option<String>, _>("legacy_body"))
               .unwrap_or_default();
```

**Comment by blackbeam** [comment]
I think you're right. `(get|take)_opt` may be useful symmetric addition to `get` and `take`.
Could you please alter return type of both to `Option<Result<T, Value>>`? Obviously `None` if value was taken, `Err` with original value if conversion error occurred and `Ok` on success.

**Comment by zacharygolba** [comment]
Ok! I'll update the PR as soon as I have moment. :)

**Comment by blackbeam** [comment]
Thanks!
But there is one more thing: documentation still states that `None` will be returned in both convertion error and taken column cases.

**Comment by zacharygolba** [comment]
No problem! I updated the docs. Let me know if you would like any additional changes.

**Comment by blackbeam** [comment]
Published as v11.3.0. Sorry for delay.

**Comment by zacharygolba** [comment]
No worries! Thank you! :)

**Pull request merged**
