### PR TITLE
Large conditional compilation refactoring

### PR DESCRIPTION
**Pull request by DenisKolodin**
I've created this PR as a first step to cross-platform compilation without features patching.
This implementation of IO is flexible and don't need a lot of duplications.

### CODE REVIEW

**Comment by DenisKolodin** [comment]
I'm moving forward with improvements in this PR. I'll notify when it's done.

**Comment by DenisKolodin** [comment]
@blackbeam I've done it. Could you check it, please?
Code becomes lesser and simpler to maintain, and it's possible to compile it without features patching.
I added myself as author if you don't mind.

**Comment by blackbeam** [comment]
Hi!

Thanks a lot for contribution! It's a pain to support these many feature intersections.
I still need to look deeper into consequences of this PR. Especially measure performance impact since it introduces dynamic dispatch IO operations.
It will take some time because my windows testing facility is quite limited at the moment.
I'm working on it.

> I added myself as author if you don't mind.

Sorry, but i do mind. First of all it's a bit unfair to all other [contributors](https://github.com/blackbeam/rust-mysql-simple/graphs/contributors), and also Cargo.toml doesn't looks like a good target to bloat it with a contributors list. Just imagine Cargo.toml in case of 57 contributors of regex or 31 contributors of rust-postgres. I believe that this field of Cargo.toml should have been named *owners* or something. For people who publishes a crate as a way to contact them
I'm not sure if this is an issue for you. If it is, than maybe there is another way to solve it?
Any way i will mention you in upcoming release notes.

**Comment by DenisKolodin** [comment]
Sounds resonable ) Ok, I'll drop the last commit soon.
I put it last to keep a chance to remove it, because merging of this improvements is the only thing I'm really interesting in.

**Comment by DenisKolodin** [comment]
I removed that commit, but CI tests have not restarted.
I think it's better to start it again, doesn't it?

**Comment by DenisKolodin** [comment]
AppVeyor can't download Rust. Could you restart it?

**Comment by blackbeam** [comment]
> **DenisKolodin**: I've fixed it with PR #71

Looks like it does not fix the #70 (see appveyor error), but i think it can.


First part of a solution is to specify target for openssl dependency:
```
[target.'cfg(any(target_os = "unix", target_os = "macos"))'.dependencies.openssl]
```
and replace every `#[cfg(feature = "openssl")]` and `#[cfg(feature = "ssl")]` with `#[cfg(all(feature = "ssl", any(target_os = "unix", target_os = "macos")))]`

Second part of a solution is to merge `socket` and `pipe` feature into `socket` feature. Also using `target_os` bound.

Do you have time to work on it?
If not, then i will implement it myself later (i want to publish alpha of mysql_async first).

**Comment by DenisKolodin** [comment]
Ok, I see the problem. It had happened, because no `gcc` installed to build `openssl` for Windows, but It's possible: I do it successfully with local environment.
I think we should update AppVeyor config to build it with `openssl`. I can do it. Any caveats?

**Comment by blackbeam** [comment]
I think the proper way to support *ssl* feature on Windows is the **schannel** crate.

Proposed solution is a placeholder of *ssl* support on Windows.
This solution will allow *ssl* to compile on windows but actually in "not implemented" state.
I am planning to add `[target.'cfg(any(target_os = "windows"))'.dependencies.schannel]` later and implement *ssl* for Windows.

**Comment by DenisKolodin** [comment]
Anything you say ;) I'll fix it with your approach from https://github.com/blackbeam/rust-mysql-simple/pull/71#issuecomment-251934995

**Comment by DenisKolodin** [comment]
I see that `named_pipes` is Windows only feature. Am I right to use it dependency for Windows builds only?

**Comment by blackbeam** [comment]
> I see that named_pipes is Windows only feature.

Yeah.

> Am I right to use it dependency for Windows builds only?

Proposed change is to unify `pipe` and `socket` feature to `socket` feature by amending `Cargo.toml` to something like this:
```toml
[features]
socket = ["named_pipe"]
...

[target.'cfg(target_os = "windows")'.dependencies.named_pipe]
...
```
and merging every `socket` and `pipe` related code and values using `#[cfg(all(feature = "socket", target_os = "windows"))]` and `#[cfg(all(feature = "socket", any(target_os = "unix", target_os = "macos")))]` attribute.

**Comment by DenisKolodin** [comment]
Ok, I've made `named_pipe` conditional. Tests passed.
I rewrite some conditions. Could you check I hadn't skipped some tests accidentally?

It's good idea to join `pipe` with `socket` feature, but let's do it as separate PR, because we'll change features set. It's won't 100% backward compatibility change. But I tend to keep this PR fully compatibility.

**Comment by blackbeam** [comment]
Looks like there is a bug in `named_pipe`.
I'll merge as soot as I fix it.

**Comment by blackbeam** [comment]
Well. Now it looks like appveyor problem 😞 
Related: http://help.appveyor.com/discussions/problems/5406-mysql-connection-via-named-pipe

**Comment by DenisKolodin** [comment]
It's bad news. It worked before?

**Comment by blackbeam** [comment]
Looks like failed tests never been run before, i think, because of incorrect cfg attributes.

**Comment by DenisKolodin** [comment]
Then we should test them locally. Ok, I'll try to find some time to check it. Or had you checked it locally yet?

**Comment by blackbeam** [comment]
It works locally so i bet that it's appveyor-related problem.
I'm a bit curious about an appveyor support response, but tomorrow i will merge this anyway.

**Comment by DenisKolodin** [comment]
I think you are right! Write me if you need any help/change.

**Pull request merged**
